### ISSUE TITLE
+smcp limitations

### ISSUE THREAD

**Issue by RGB-es** [Fuzzypeg/Coelacanth#17]
The screenshot shows three problems with the +smcp feature enabled:

- diacritics do not work 
- there is a problem with the italic variants with a mix of italic for the full caps and roman for the small caps
- the Qu ligature does not work there

![Coelacant-smcp](https://user-images.githubusercontent.com/7756783/103586728-f92ec000-4ee5-11eb-8bcb-e7a51d62014b.png) 

BTW, many thanks for this amazing project!

**Comment by Fuzzypeg** [comment]
Letters with diacritics now work correctly with smcp, pcap, c2sc and c2pc.
I still need to modify the usage of Q with long tail, so it is used before all smcp and pcap glyphs except j. I will move that to a separate issue so I can close this one.

**Comment by Fuzzypeg** [comment]
Expanding use of Q.alt has been split to issue #24 . Closing this issue as complete.
