### ISSUE TITLE
A variant of f would be useful.

### ISSUE THREAD

**Issue by philipt18** [Fuzzypeg/Coelacanth#33]
I ran into an interesting problem last night. I was trying to upload a manuscript to KDP, and it returned a ton of errors. It required me to shift the gutter (inside margin) which I did, and then I still had a ton of errors. The new errors, however, were all caused by a single letter, f. In a given text frame, whenever f was on the inside margin (i.e. on the right side of the left-page of a spread) the f extended outside the text frame just enough to trigger KDP to say it was outside the margin. There is an alternative glyph for f which is a bit narrower which helps (although I'm not sure if it still passed the text frame - I had already shifted the frame over a bit). However, one case had no easy fix, where there was an italic f on the left side of the right-page of a spread. In this case the bottom of the f went way outside the frame, and the alternative glyph didn't help at all.

I think it would be helpful for both f and italic f if there were variants that did not pass the text frame on either side. That might require two variants for the italic f (one that doesn't pass the left side of the frame, and one that don't pass the right side of the frame.

After a bit of searching I found this is a known problem with the letter f in many fonts. Its kind a of a stupid problem since it's KDP being overzealous about margins, but having alternates to quickly fix these issues would save a lot of work when running into this issue.

**Comment by Fuzzypeg** [comment]
This is really a problem with KDP, not with the font. I can see others have proposed solutions such as enabling full bleed, adjusting margins etc. The problem affects many fonts, not just this one. To fix this via the font would require messing up the basic spacing of several characters and then compensating for that bad spacing through extensive kerning rules. For italics, this would need to be done for a vast number of glyphs. It just seems too much work and not the appropriate place to make the fix.

Anyway, this repo is moving to https://gitlab.com/Fuzzypeg/coelacanth. If you'd like to discuss further, feel free to open a new ticket there.
