### ISSUE TITLE
Hungarian umlaut

### ISSUE THREAD

**Issue by mesti90** [Fuzzypeg/Coelacanth#6]
Would it be possible to change the long Hungarian umlaut? I would like to have the two top of the two accents at the same level, and for the bottom the same.
![image](https://user-images.githubusercontent.com/30521525/52919275-072ec400-3301-11e9-93e2-89809f352437.png)

**Comment by mesti90** [comment]
Here you see the requested font face for the given characters:

![image](https://user-images.githubusercontent.com/30521525/64922769-4956b000-d7d3-11e9-9350-0f3f3a108573.png)

**Comment by Fuzzypeg** [comment]
Fixed so far for regular weight at all optical sizes. Need to complete the fix for hairline and gross weights at all sizes. I've changed the double-acute (uni030F, Uni030F) to match the Hungarian umlaut reversed.

**Comment by Fuzzypeg** [comment]
I believe this should be fixed for all sizes and weights now (roman fonts only). Available in the next release.
