### ISSUE TITLE
c2sc and c2pc glyphs but no features

### ISSUE THREAD

**Issue by svenper** [Fuzzypeg/Coelacanth#7]
For example Ẍ Ộ ẞ (among many more) have glyphs but not features to make them small caps.

**Comment by Fuzzypeg** [comment]
Yes, this needs updating for all glyphs. Regarding "ß", though, usual preferred style is to capitalise this to "SS"; the capital "ẞ" glyph is a fairly modern invention. So converting to small-caps or petite-caps should probably use small/petite-cap "ss". Small/petite "ẞ" could be made available as an alternative via another opentype option, or perhaps I'll leave it for manual use. Not yet sure.

**Comment by Fuzzypeg** [comment]
Whoops, disregard my comment about capital "ẞ" for c2sc and c2pc. I was thinking of smcp and pcap. When converting from capitals there's no ambiguity.
The point remains that the lookups are incomplete for c2sc, c2pc, smcp and pcap.

**Comment by Fuzzypeg** [comment]
Fixed. Should be available in the next release.
